// Code generated by MockGen. DO NOT EDIT.
// Source: ./url_manipulations.go

// Package urlmanipulations_test is a generated GoMock package.
package urlmanipulations_test

import (
	gomock "github.com/golang/mock/gomock"
	url "net/url"
	reflect "reflect"
)

// MockCallerURL is a mock of CallerURL interface
type MockCallerURL struct {
	ctrl     *gomock.Controller
	recorder *MockCallerURLMockRecorder
}

// MockCallerURLMockRecorder is the mock recorder for MockCallerURL
type MockCallerURLMockRecorder struct {
	mock *MockCallerURL
}

// NewMockCallerURL creates a new mock instance
func NewMockCallerURL(ctrl *gomock.Controller) *MockCallerURL {
	mock := &MockCallerURL{ctrl: ctrl}
	mock.recorder = &MockCallerURLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCallerURL) EXPECT() *MockCallerURLMockRecorder {
	return m.recorder
}

// Call mocks base method
func (m *MockCallerURL) Call(url *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call
func (mr *MockCallerURLMockRecorder) Call(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockCallerURL)(nil).Call), url)
}
